name: Node Setup
description: Setup Node.js environment for OctoDash CI workflows

runs:
  using: composite
  steps:
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        env:
          cache-name: node-modules
        with:
          path: '**/node_modules'
          key: octodash-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            octodash-build-${{ env.cache-name }}-
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install latest npm
        shell: bash
        run: sudo npm install -g npm@latest
      - name: Installing Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        shell: bash
        run: npm ci
      - name: NPM Prepare
        shell: bash
        if: steps.cache-node-modules.outputs.cache-hit == 'true'
        run: npm run prepare