on: workflow_call

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: node-modules
        with:
          path: '**/node_modules'
          key: octodash-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            octodash-build-${{ env.cache-name }}-
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install latest npm
        run: sudo npm install -g npm@latest
      - name: Installing Dependencies
        run: npm ci
      - name: Building Application
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angular
          path: dist/
