on: workflow_call

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/setup.yaml
      - name: Building Application
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angular
          path: dist/
